### ISSUE TITLE
Unexpected behaviour: Repeated + raises KeyError

### ISSUE THREAD

**Issue by bashtage** [matthewwardrop/formulaic#10]
Running

```
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.standard_normal((100,3)),columns=["y","y2","x"])
from formulaic import model_matrix
dep = model_matrix("y ~ 1 + + x", df, ensure_full_rank=False)
```

produces KeyError: '++'. This also seems to be an issue in the tokenizer. FWIW patsy would parse this as "y ~ 1 + x"

I found these running part of the test suite for linearmodels using formulaic.

**Comment by bashtage** [comment]
Also strange with "y ~ 1 + -x"

**Comment by matthewwardrop** [comment]
This is actually intended behaviour in formulaic, modulo the unhelpful error message which will be improved soon.

When parsing formulas, formulaic currently ignores whitespace, and allows people to customise the operator handling however they wish (including adding a `++` or `+-` operator for cases like these, or other operators of their choosing like `%in%`).

I personally would find formulas written like this confusing, but it looks like R coalesces `++` and `+-` into `+` and `-` respectively, and always treats `+` and `-` as unary operators when adjacent to another operator. Patsy also coalesces `++` to `+`, but throws an error on `+-` or similar combinations.

Given that I'd like to maximise compatibility with R, I think there's a legitimate use-case here to support these kinds of operators. A naive way would be to literally add handling for operators like `++`, `+-`, `*+`, `*-`, etc; but the number of operators you would need to be complete is a bit annoying. I think I'll an extra step to the infix-to-ast processor that allows operators to be "greedy", effectively splitting tokenised operators into two or more operators if the beginning of the operator matches a greedy operator type. This would allow formulaic to support these use-cases without having to manually add all the possible combinations.

Any thoughts on this approach?

**Comment by matthewwardrop** [comment]
![image](https://user-images.githubusercontent.com/124910/87898926-72a02800-ca04-11ea-893b-c727930fd8c7.png)

**Comment by bashtage** [comment]
Great.  I should finish initial testing this week and be able to have it available as an option in linearmodels.
