### ISSUE TITLE
version number == 0.0.0

### ISSUE THREAD

**Issue by DavidWalz** [matthewwardrop/formulaic#105]
Just cosmetics but it seems like the version number is not updated in the build pipeline
```
pip install formulaic>=0.5
...
python -c "import formulaic;print(formulaic.__version__)"
0.0.0
```

**Comment by matthewwardrop** [comment]
Thanks for reporting! I fixed this in https://github.com/matthewwardrop/formulaic/commit/b6a456b3233718fcd187fefd01a95546161d0df5 .
