### ISSUE TITLE
Sparse matrix creation is slow

### ISSUE THREAD

**Issue by dbalabka** [matthewwardrop/formulaic#109]
It seems that sparse matrix creation is extremely slow on large datasets with many categories (~1M million rows and ~10K of categories). I suspect that it might be related to the complexity of the algorithm:
https://github.com/matthewwardrop/formulaic/blob/14487a1e1a994f2f2f10197d91489ee895ee2a6e/formulaic/utils/sparse.py#L42-L43

I have prepared changes that simplify the code and make it much faster.

**Comment by matthewwardrop** [comment]
Thanks again for the patch! I've merged your PR with some fixes. I'll try to get a new release out some time soon.

**Comment by dbalabka** [comment]
@matthewwardrop, thanks for merging it into master 🥳 

Right after the new release will be published, I'm going to propose updating the formulaic library for the linearmodels library. Currently, it depends on `formulaic~=0.3.2`. Still, it might be complicated because of BC breaks.
