### ISSUE TITLE
bug: incorrect metadata license file

### ISSUE THREAD

**Issue by b-kamphorst** [matthewwardrop/formulaic#119]
Hi! It appears that the `formulaic` wheel metadata is faulty for the license file. It states `License-File: LICENSE`, but the license file is located in `licenses/LICENSE`. As a result, e.g. `pip-licenses` is unable to determine the license:

```bash
# pip-licenses -p formulaic
 Name       Version  License 
 formulaic  0.5.2    UNKNOWN 
```

The metadata was fine for version 0.4.0:

```bash
# pip-licenses -p formulaic
 Name       Version  License     
 formulaic  0.4.0    MIT License 
```

As such, I expect that this is an issue in the `hatching` back-end that you migrated to in 0.5.0. However, I'm not familiar with that so I'll leave the assessment and possible propagation to the community.

**Comment by matthewwardrop** [comment]
Hi!

Thanks for reporting this. I checked with latch upstream, and it looks like they have adopted PEP 639 pre-emptively, which defines this behavior concretely (vs implicitly as before).

If you are using `pip-licenses`, I'd suggest raising an issue with them, and see if they might not add support for this.

Closing this one out.

**Comment by b-kamphorst** [comment]
Hi @matthewwardrop thank you so much for looking into this and providing a clear answer! I've reported this back to `pip-licenses` so that they can improve their tool.
