### ISSUE TITLE
Allow interaction with yourself

### ISSUE THREAD

**Issue by amichuda** [matthewwardrop/formulaic#120]
When I run a formula with a variable "interacted with itself" like this:

```python
import pandas as pd
from formulaic import model_matrix

df = pd.DataFrame({'a' : [1,2,3]})

model_matrix("a*a", data=df)

   Intercept  a
0        1.0  1
1        1.0  2
2        1.0  3
```

I get this dataframe. Is this by design? Or is there a way to get:

```python
   Intercept  a a:a
0        1.0  1   1
1        1.0  2   4
2        1.0  3   9
```

without using `poly` explicitly?

**Comment by matthewwardrop** [comment]
Hi @amichuda ,

Thanks for reaching out.

Multiplication in formulae means something different than regular multiplication (its basically a bunch of set unions); e.g. a*b*c |-> a + b + c + a:b + a:c + b:c. To do regular multiplication, you can use the `{...}` syntax; e.g.:

```python
>>> import pandas as pd
>>> from formulaic import model_matrix
>>> df = pd.DataFrame({'a' : [1,2,3]})
>>> model_matrix("a + {a**2}", data=df)
   Intercept  a  a**2
0        1.0  1     1
1        1.0  2     4
2        1.0  3     9
```

You can learn more about the formula grammar here: https://matthewwardrop.github.io/formulaic/ .

I'll close this issue out for now, but feel free to continue chatting below if you need more help :).
