### ISSUE TITLE
DOC: Explicitly mention support for multiple variables on the left hand side

### ISSUE THREAD

**Issue by s3alfisc** [matthewwardrop/formulaic#125]
Hi Matthew, 

Yet another question: Are multiple variables on the left hand side supported? It seems like it, but I wanted to be sure before I build on it: 

```
from formulaic import model_matrix 
import numpy as np
import pandas as pd

N = 10
X = np.random.normal(0, 1, N)
Y = np.random.normal(0, 1, N)
Y1 = np.random.normal(0, 1, N)
Y2 = np.random.normal(0, 1, N)

data = {'Y1':Y1, 'Y2':Y2, 'X':X}
data = pd.DataFrame(data)

fml = 'Y1 + Y2 ~ X'
y, X = model_matrix(fml, data, na_action = 'ignore')
>>> y.head()
         Y1        Y2
0 -0.949247  2.510162
1 -0.695311 -0.727821
2 -0.072459 -1.172503
3  0.422692 -1.223921
4  0.224729  0.585468
```

Best, Alex

**Comment by matthewwardrop** [comment]
Hi @s3alfisc ,

Yes... multiple variables can be added to the left-hand-side :). The only difference is that the intercept is not added by default.

**Comment by s3alfisc** [comment]
Super cool, thanks for your response!

**Comment by matthewwardrop** [comment]
This is now documented here: https://matthewwardrop.github.io/formulaic/migration/
