### ISSUE TITLE
DOC: One-hot vs. Dummy Encoding

### ISSUE THREAD

**Issue by rluedde** [matthewwardrop/formulaic#13]
The [Quickstart](https://matthewwardrop.github.io/formulaic/basic/quickstart/#fn:1) page says

> You will notice that the categorical values for a have been one-hot encoded

Would it be more accurate to say that they categorical values have been dummy encoded? It seems to me (knowing nothing about encoding until an half an hour ago), that one-hot encoding adds `k` columns to the `X` matrix and dummy encoding adds `k-1` columns. It looks like you add `k-1` because one gets dropped?

**Comment by matthewwardrop** [comment]
Good catch. Under the hood the columns *are* one-hot encoded, but then during the rank reduction steps this transforms most of the time (but not always) to a dummy encoding. I'll keep this issue around so I can hopefully clarify this :).

**Comment by DWesl** [comment]
Going by the patsy docs on dummy encoding:
https://patsy.readthedocs.io/en/latest/API-reference.html#categorical-coding-ref
and the scikit-learn docs on one-hot encoding:
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html#sklearn.preprocessing.OneHotEncoder
I think the difference between dummy encoding and one-hot encoding is whether the person describing the encoding has a statistics background or a machine learning background.

**Comment by matthewwardrop** [comment]
Aye... looks like there is no difference after all (but I've added both nomenclatures to ensure that people familiar with the different nomenclature are not confused. Thanks again!
