### ISSUE TITLE
How do I set the reference level for a categorical term?

### ISSUE THREAD

**Issue by laserson** [matthewwardrop/formulaic#130]
I'd like to define the level that should be used as the reference level in my formula string. Is it possible to do so with the current implementation?

**Comment by matthewwardrop** [comment]
Hi @laserson ,

Sorry for the delay. I must have missed the notification! And thanks for reaching out.

Yes, this is presently possible. You can do, for example:

`model_matrix("y ~ C(x, contr.treatment(base='ref'))",...)`

You can omit `base=` if you like.

I'll leave this issue open until the documention has been updated.

Best,
M

**Comment by laserson** [comment]
Thanks @matthewwardrop! I did go spelunking through the code some but couldn't figure out where I'd find this. Could you point me to the relevant lines that show how the parser would now about that function?

**Comment by matthewwardrop** [comment]
Sure!

The ContrastsRegistry (https://github.com/matthewwardrop/formulaic/blob/7f1c3483707279c24a1beff897fdbbddfbf343a8/formulaic/transforms/contrasts.py#L673) becomes aliased as `contr` in the dictionary of available transforms (https://github.com/matthewwardrop/formulaic/blob/7f1c3483707279c24a1beff897fdbbddfbf343a8/formulaic/transforms/__init__.py#L21). This dict is automatically added to the expression evaluation context (https://github.com/matthewwardrop/formulaic/blob/7f1c3483707279c24a1beff897fdbbddfbf343a8/formulaic/materializers/base.py#L126). Hope that helps!

Best,
M

**Comment by laserson** [comment]
Super helpful, thanks!!
