### ISSUE TITLE
Escaped variables and functions

### ISSUE THREAD

**Issue by bashtage** [matthewwardrop/formulaic#151]
I believe that in some earlier versions that combinations of escaped variables and functions worked. For example

```
formula = "y ~ 1 + np.exp(`x 1`)"
```

This does not work on the latest formulaic. Do you know if this is expected? Or is it an unintentional regression?

**Comment by matthewwardrop** [comment]
That is indeed a regression (apologies for the delay... life has been hectic). Will patch in the next release.

**Comment by bashtage** [comment]
Thanks for the quick fix.

**Comment by matthewwardrop** [comment]
You're welcome! This is now published in 0.6.5 :).
