### ISSUE TITLE
Add a "safe" mode that avoids using `eval`?

### ISSUE THREAD

**Issue by matthewwardrop** [matthewwardrop/formulaic#17]
In some cases, particularly in production code, it is nice to have a safe mode that avoids using `eval`, at the expense of some functionality. This issue is here so this line of thought doesn't get lost, but also to see how important this is to people.

To be clear, removing `eval` in the current state would basically cripple Formulaic by preventing any Python transformations (including built-in transformations). There may be a middle ground whereby we introspect the generated Python code AST, and verify that the functions to be executed are sanctioned.

**Comment by matthewwardrop** [comment]
This is related to an issue on patsy https://github.com/pydata/patsy/issues/156, where @FerusAndBeyond points out that running:

```
from formulaic import model_matrix
model_matrix('sys.exit()', ...)
```

will kill the running python service. Is there a way to protect formulaic from code injection?

**Comment by tomicapretto** [comment]
At the moment, formulae does not use `eval()` (see [here](https://github.com/bambinos/formulae/blob/f5ea0ec8be5a422638db18f78296b3bc74d54c2f/formulae/terms/call_resolver.py#L241-L268)), but it is still vulnerable to `sys.exit()` calls if you have `sys` loaded in the environment where `design_matrices()` is called. 

I do think we could port something similar to Formulaic and attempt to ban people calling functions from certain modules.

**Comment by matthewwardrop** [comment]
I'm going to close this for now. With proper context isolation (which libraries can already control), the use of `eval` seems pretty sensible. Avoiding it as suggested by @tomicapretto basically means manually parsing the syntax tree and calling the function anyway. In both cases, since Formulaic parses the AST anyway, we *could* deny use of particular functions... but I don't see this being especially valuable. If this ever comes up again we can refresh this issue.
