### ISSUE TITLE
Add . operator

### ISSUE THREAD

**Issue by memeplex** [matthewwardrop/formulaic#175]
As in R formulae.

`.` denotes "everything else". E.g. `y ~ .` regress `y` on all other variables in a data frame.

Useful in combination with `-`.

**Comment by matthewwardrop** [comment]
Thanks for the suggestion @memeplex . I'll consider adding this in the next major release.

**Comment by matthewwardrop** [comment]
Support for this is now going into `main`! Not expecting many in common usage, but if you find any edge-cases where this doesn't work well, let me know @memeplex !
