### ISSUE TITLE
Creating strict sub-models from a model

### ISSUE THREAD

**Issue by bashtage** [matthewwardrop/formulaic#193]
I have started working on getting formulaic into [statsmodels](https://github.com/statsmodels/statsmodels). Very, very early start in statsmodels/statsmodels#9419. 

While much is pretty straightforward and just needs care (e.g., dmatrix/dmatrices -> model_matrix, design_info -> model_spec), one common issues I've found is subsettign a model.  One simple example is the need to drop an Intercept if present. So if my original model was `y ~ 1 + x + z` I would need the model `y ~ x + z` . In patsy one can directly drop terms from a `DesignInfo` instance and then rerun. Is there an easy (and correct (and canonical if possible)) way to drop variables? 

Also, is the intercept special in any way? Patsy has a special singleton term INTERCEPT that is always used when there is an explicit intercept in a model.  This makes it really eacy to check each term to see if that are the singleton INTERCEPT. Is anything similarly available in formulaic?

Many thanks for any pointers.

**Comment by matthewwardrop** [comment]
Can you give me a little more context on why this is necessary and what kind of levers are necessary? What does it mean to drop a variable? Is it more the dropping of terms? What does that mean in the context of categorical datesets?

`ModelSpec` instances provide various slices to allow you to subset model matrices, but no tools (as yet) to modify the model spec itself.

In formulaic, there's nothing special about the intercept (except that we add one by default prior to building the AST). Why is that necessary?

**Comment by bashtage** [comment]
One scenario that is in sm is to get the terms without the intercept.  These are then used in some additional statistical analysis.  The easy way is to recreate the the regressor matrix after deleting the intercept, which is patsy is always a special singleton value, and so can always be found if present.  In formulaic I can look for the term named Intercept with 1 as the ... (sorry forgot the property that is 1). Seems pretty reliable but not quite as simple as searching for a specific term using `term is INTERCEPT`.

**Comment by matthewwardrop** [comment]
I think, based on (comments in statsmodels](https://github.com/statsmodels/statsmodels/pull/9423#discussion_r1845259045), that this really isn't something that we'd need to add better support for; since you have already identified the way to identify the term corresponding to the global intercept. If you think we need to do more here, let me know, but otherwise I'm inclined to close this issue as there isn't really much to do here. Is there additional functionality you'd like to see?
