### ISSUE TITLE
No way to retrieve and reuse drop_index when na_action='drop'

### ISSUE THREAD

**Issue by andrejmuhic** [matthewwardrop/formulaic#195]
Thank you for writing this library.
I have added pull request that enables this, I would appreciate your insight as I am not sure what is the best way to handle this.
Also maybe I missed something.
https://github.com/matthewwardrop/formulaic/pull/194

**Comment by matthewwardrop** [comment]
@andrejmuhic I've merged in support for this as described in #197 :). Let me know if this doesn't work for you.

**Comment by andrejmuhic** [comment]
@matthewwardrop Thank you for this. I think this will work nicely.
I will test it out soon. I am not a big fan of passing results by modifying arguments in python but your solution seems more pragmatic.
