### ISSUE TITLE
What are the limitations from treatying formulaic as a drop-in replacement for patsy?

### ISSUE THREAD

**Issue by bashtage** [matthewwardrop/formulaic#2]
Aside from not supporting recarrays (which is sensible), are there any known limitations?

**Comment by matthewwardrop** [comment]
Hi again @bashtage ,

The formula grammar should be largely identical, however there are transformations that I have not implemented. For example, I have not implemented support for arbitrary contrast matrices. Support can easily be added for these things, I just haven't needed them for my use-cases. I am not aware of any limitations from a framework perspective. If something in particular is valuable to you, I can definitely look at including it.

The API is different, obviously, so you won't be able to just import formulaic and have everything work transparently.

**Comment by matthewwardrop** [comment]
I put some time today into documentation. It doesn't render quite as well as it will in mkdocs, but you can see a comparison of the grammars here: https://github.com/matthewwardrop/formulaic/blob/a19ebfd77c8129fd5827218588053432b489e7a9/docs/basic/formulas.md .

**Comment by bashtage** [comment]
Thanks. statsmodels would definitely be interested in picking up formulaic. statsmodels/statsmodels#6858 We have models that have formulas in R but we can't support with patsy, which has proven hard to extend.

**Comment by josef-pkt** [comment]
Does formulaic avoid `eval` and allows pickling of formula information?

**Comment by matthewwardrop** [comment]
@josef-pkt `eval` is avoided when there are no python transforms involved (e.g. https://github.com/matthewwardrop/formulaic/blob/master/formulaic/materializers/base.py#L283). As soon as there are Python transforms involved, an `eval` will occur. Code is compiled into an abstract syntax tree, modified slightly, and evaluated (e.g. https://github.com/matthewwardrop/formulaic/blob/ba2bac81c21457ee1fa1e50fbbac66d305c374b9/formulaic/utils/stateful_transforms.py#L90). It seems feasible in principle to compile the abstract syntax tree, and derive any information you need from it without actually having to run an `eval`. It would be tricky if your transforms require nested Python objects, but it seems doable. Perhaps there is motivation enough for a 'safe mode'?

As for pickling... yes. Formulas and ModelSpec instances can be pickled.

**Comment by josef-pkt** [comment]
There was recently a stackoverflow question, that I don't find anymore, asking for a safe eval in patsy when users of their program provide the formula string.

I never really use eval, but something that restricts what can be run in formula strings would be good to have for users that get formula strings from someone else.

In general I think avoiding eval or having a safe eval would be good to have also if it doesn't allow all features. 
(E,g, I think it's weird that R formulas take the data from the outer scope when users don't provide them explicitly. That's too much magic for my taste.)

**Comment by matthewwardrop** [comment]
Aye. This "magic" by formulaic in its `model_matrix(..)` sugar method, largely for compatibility with expectations from patsy, but also because it is sometimes convenient. If you use the `Formula(...).get_model_matrix(..)` this magic does not occur.

I'll add an issue for later thought about adding a safe mode!

**Comment by bashtage** [comment]
Was support for contrasts added yet? That was the one piece missing as far
as statsmodels is concerned.

**Comment by matthewwardrop** [comment]
Not yet! I'll bump it up the priority list.
