### ISSUE TITLE
Build new ModelMatrix using state of existing ModelSpec

### ISSUE THREAD

**Issue by klaapbakken** [matthewwardrop/formulaic#20]
Hi Matthew. This looks like a very promising package. I'm hoping to use this instead of `patsy` as soon as the API has matured. I'm therefore doing some experimentation with it in its current state. The reason I want to move away from `patsy` is that it does not support pickling `DesignInfo`. One feature of `patsy` that is critical to me though, is the ability to build new design matrices using an already existing `DesignInfo` object. This is supported in `patsy` through `build_design_matrices`. Can this be achieved using `formulaic` as well? It seems to me like calling `get_model_matrix` automatically recomputes the state (like the mean used in center()) using the supplied dataset. I would like to be able to use the state of an already existing `ModelMatrix`/`ModelSpec` when creating a new `ModelMatrix`. Is this currently supported?

**Comment by matthewwardrop** [comment]
Hi @klaapbakken ! This functionality is indeed supported via the `ModelSpec` class. You can access the `ModelSpec` instance associated with a model matrix generated by `get_model_matrix`, e.g.:

```
from formulaic import model_matrix

df = ....
mm  = model_matrix('y ~ x', df)
ms = mm.model_spec
```

You can then use that model spec to generate a new model matrix from new data using:
```
mm2 = ms.get_model_matrix(df2)
```

Hope that helps! In lieu of better documentation (still coming!), you can view the `ModelSpec` class here: https://github.com/matthewwardrop/formulaic/blob/master/formulaic/model_spec.py

**Comment by matthewwardrop** [comment]
I'll leave this open until this has been properly integrated into the docs.

**Comment by fabio-rosa-ors** [comment]
Hi Matthew. Great work !
I'm using the suggested approach to save/restore the state of ModelSpec within our ML framework with success, so I would suggest just a small sugar addition to catch the context when using the recovered ModelSpec: in my work I found very useful to include this utility under sugar.py
```
def get_model_matrix(model_spec, data, *, context=0, **kwargs):
    if isinstance(context, int):
        if hasattr(sys, "_getframe"):
            frame = sys._getframe(context + 1)
            context = LayeredMapping(frame.f_locals, frame.f_globals)
        else:
            context = None  # pragma: no cover
    return model_spec.get_model_matrix(data, context=context, **kwargs)
```
the body is the same as model_matrix, but with different Materializer introduced by the model_spec param.

In the previous example ms2 could be used like here:
`mm2 = formulaic.get_model_matrix(mm2, df2)`
with the effect of catching custom transformer referred by the formula

**Comment by matthewwardrop** [comment]
Excellent idea @fabio-rosa-ors ! I've incorporated this into the `model_matrix` sugar method, so now you can just do:

```
model_matrix(<old model matrix>, <new data>)
```

Will be in Formulaic 0.3

**Comment by fabio-rosa-ors** [comment]
Great !
