### ISSUE TITLE
Question about Statsmodels dependency swap patsy for formulaic

### ISSUE THREAD

**Issue by amaranthjinn** [matthewwardrop/formulaic#228]
The recommendation for patsy usage is to migrate to formulaic, however, our team wants to use statsmodels, which listed patsy as its minimum dependency https://www.statsmodels.org/stable/install.html#dependencies.
Is formulaic compatible with statsmodels that replacing patsy with formulaic (in the dependency specification) is sufficient for statsmodels to work? Or are there additional steps needed?

**Comment by matthewwardrop** [comment]
`statsmodels` has not yet released a stable version that uses `formulaic`, but it is underway: https://github.com/statsmodels/statsmodels/pull/9423 (thanks to the work of @bashtage ).

In the meantime, it remains safe to use `patsy`, which has received the minimal maintenance required to keep it functioning until more use-cases are fully migrated to `formulaic`.

**Comment by bashtage** [comment]
The main branch of statsmodels supports formulaic (but it isn't the default).  This support should be out in the next release.
