### ISSUE TITLE
Rip a new release

### ISSUE THREAD

**Issue by CamDavidsonPilon** [matthewwardrop/formulaic#26]
👋 Hi Matt, do you have an approximate timeline for a new release?

**Comment by griffiri** [comment]
hi - any update on a new release? many thanks

**Comment by matthewwardrop** [comment]
Hi @CamDavidsonPilon @griffiri ! Sorry! Work has been crazy over the past few months. I'm going to use some of my Christmas "break" to polish and release a new version :).

**Comment by griffiri** [comment]
Awesome, thanks! Hope you are not drinking too much while working on it :)

**Comment by griffiri** [comment]
hi Matt - any update on the new release?

**Comment by matthewwardrop** [comment]
Hi @griffiri ! Sorry again. I keep being optimistic about having more time to properly prepare some changes to the API (between my work, the pandemic and my four kids), so for now I'm just going to release it as is. I've release v0.2.0 now. The good news is that I will be needing this project for some work I'm about to land for my paid job... so it should get a bit more attention.

**Comment by griffiri** [comment]
Thanks @matthewwardrop ! Surprised you manage to do anything with 4 kids, given my experience with 1....

**Comment by CamDavidsonPilon** [comment]
Thanks @matthewwardrop!
