### ISSUE TITLE
Determine which input columns were used to generate output columns

### ISSUE THREAD

**Issue by eric-czech** [matthewwardrop/formulaic#32]
Great library @matthewwardrop! 

Is there a way to determine how input columns correspond to output columns in an example like this?

```python
import pandas
from formulaic import model_matrix

df = pandas.DataFrame({
    'y': [0, 1, 2],
    'a': ['A', 'B', 'C'],
    'b': [0.3, 0.1, 0.2],
})

y, X = model_matrix("y ~ a + b + a:b", df)
X
```

Intercept | a[T.B] | a[T.C] | b | a[T.B]:b | a[T.C]:b
-- | -- | -- | -- | -- | --
1.0 | 0 | 0 | 0.3 | 0.0 | 0.0
1.0 | 1 | 0 | 0.1 | 0.1 | 0.0
1.0 | 0 | 1 | 0.2 | 0.0 | 0.2

For example, I would like to know that the input columns `a` and `b` were used to generated the resulting interaction field `a[T.B]:b`.  I would like to establish this through some structured, intermediate data structure though rather than parsing it back out of the names.  Does such a structure exist and is it easy to access?

Thanks!

**Comment by matthewwardrop** [comment]
Hi @eric-czech !

Thanks for reaching out! Unfortunately formulaic doesn't (yet?) contain this functionality.

As you may already be aware, model matrices output by `formulaic` are wrapped in a `ModelMatrix` proxy class, which has an attribute `.model_spec`. While there isn't a direct mapping of input dataframe to columns, there is a term to columns map:
```python
X.model_spec.structure
```
> [(1, [1], ['Intercept']),
 (a, [a-], ['a[T.B]', 'a[T.C]']),
 (b, [b], ['b']),
 (a:b, [a-:b], ['a[T.B]:b', 'a[T.C]:b'])]

For simple cases like this you could reverse engineer the support of any particular model matrix column, but it really wouldn't be much better than parsing it out of the names; and when you start applying transforms on the columns, all bets are off.

I'm willing to add this feature if there is need, but I'm curious as to why the reverse logic is valuable in your use case!

**Comment by eric-czech** [comment]
> While there isn't a direct mapping of input dataframe to columns, there is a formula term to model-matrix-columns map

I see, thanks.  I noticed I could get similar information out of Patsy but it still looked like some parsing was going to be inevitable.

> I'm willing to look into adding this feature if there is need, but I'm curious as to why the reverse logic is valuable in your use case

Awesome!  A simple use case I have in mind would be to summarize the effects of multiple related features (e.g. one-hot encodings or polynomial basis functions) by grouping them together.  In other words, if my original feature `a` above resulted in 3 binary features then I might want to sum the coefficients from a linear model or Shapley values across all of them as a combined effect.  Another would be to simply associate features with logical groupings like the data source they were originally from, which would again be useful in downstream model interpretation.  That's certainly all possible based on the string names of generated features with more fragile, analysis-specific code (my typical go-to).

There are a few other use cases like this that I would characterize more broadly as propagation of field metadata (e.g. perhaps via [pandas.Series.attrs](https://pandas.pydata.org/pandas-docs/version/1.0.0/reference/api/pandas.Series.attrs.html) or [xarray.DataArray.attrs](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.attrs.html)).  You could imagine that if I simply attached some metadata to my feature `a`, having that metadata replicated in all features produced from it would be very useful.  I'm surprised there still doesn't seem to be a good solution for this in the scikit-learn ecosystem, but it seems like a natural extension of more extensive model matrix building tools like Patsy and formulaic.  

> the best we could probably do is outputting a list of symbols, and then allowing you to do a set difference from the columns of your incoming dataframe

Hmm would that be a list of symbols associated with each individual output column?  Sounds like that could work.

On that note, would doing `model_matrix(..., df, context=None)` ensure that the results only come from the dataframe?

**Comment by matthewwardrop** [comment]
Hi @eric-czech ! Sorry for the huge delay on this work. This should be finally resolved by #145 , after a little more tweaking. If you have some thoughts on that PR, let me know :).

**Comment by eric-czech** [comment]
> This should be finally resolved by https://github.com/matthewwardrop/formulaic/pull/145 , after a little more tweaking.

Awesome!  Looks good to me though the first question that comes to mind is whether or not it would handle interaction terms.  Might be worth including one of those in the examples?

**Comment by matthewwardrop** [comment]
@eric-czech Thanks for checking in. This functionality does indeed support interaction terms. You can even manually dig into the model spec structure to get at variables that the factor level (but this isn't surfaced at the top-level model spec API because I doubt this is a common use case).

I've cleaned up the code, and included an interaction term in the demonstration here: https://github.com/matthewwardrop/formulaic/pull/145#issuecomment-1627613862 . Let me know if you have any further concerns, otherwise I'll circle back around and add some unit testing/documentation and merge this when I get the chance.
