### ISSUE TITLE
ENH: Support for Linear Constraints

### ISSUE THREAD

**Issue by bashtage** [matthewwardrop/formulaic#38]
It would be great if it was possible to support linear constraint transformation from str to constraint arrays.

https://patsy.readthedocs.io/en/latest/API-reference.html#linear-constraints
 
I don't see any support for this and it is the final piece from me dropping patsy from [linearmodels](https://github.com/bashtage/linearmodels).

**Comment by matthewwardrop** [comment]
Roger that! I'll add some equivalent functionality into formulaic, but likely as an additional utility applied to a `ModelMatrix` rather than an attribute of it. Would that work for you? Something like:

`LinearConstraint.from_matrix(model_matrix, 'a + b = 0')`

**Comment by bashtage** [comment]
Happy to use a different API from patsy -- makes little difference in practice.  Thanks.

**Comment by matthewwardrop** [comment]
Support for this is now in `main`. You can do: `model_matrix.model_spec.get_linear_constraints(...)`.

**Comment by bashtage** [comment]
This is great, thanks.  I'll give it a whirl in the next few week.  In principle, I can now also check to see if statsmodels can switch, although it will probably be more involved with some deprecation there.

**Comment by matthewwardrop** [comment]
Sounds good! Let me know how it goes.
