### ISSUE TITLE
"Finish" documentation

### ISSUE THREAD

**Issue by matthewwardrop** [matthewwardrop/formulaic#47]
The current documentation is incomplete and full of typos. Finish it!

**Comment by rosonaeldred** [comment]
It also throws a lot of 404-not-found errors. 

E.g. 'Formula Grammar' https://matthewwardrop.github.io/formulaic/formulas/grammar.md
linked to from https://matthewwardrop.github.io/formulaic/formulas/

**Comment by matthewwardrop** [comment]
Yeah... I added the scaffold before the actual doc pages, and things
haven't been kept in sync in places. It should be fully ratified soon,
since I'm gunning to release 1.0.0 and I want the docs in place first.

**Comment by matthewwardrop** [comment]
This is completed now as of fd8cd40.
