### ISSUE TITLE
Variable (covariate) names with dashes are not parsed

### ISSUE THREAD

**Issue by erikr** [matthewwardrop/formulaic#50]
## Summary
I am analyzing Pandas DataFrame in which some variable names have dashes, e.g., `foo-bar`.

This results in an error when calling `formulaic.model_matrix`.

## Error message

```
FactorEvaluationError: Unable to evaluate factor `b`. [KeyError: 'b']
```

## Minimum reproducible example

The error is reproduced by running the following code:

```python
import pandas
from formulaic import model_matrix

df = pandas.DataFrame({
    'y': [0, 1, 2],
    'a': ['A', 'B', 'C'],
    'b-foo': [0.3, 0.1, 0.2],
})

y, X = model_matrix("y ~ a + b-foo", df)
```

## Expected behavior

The following DataFrame `X` is generated:
```
| Intercept | a[T.B] | a[T.C] | b-foo |
|-----------|--------|--------|-------|
| 1.0       | 0      | 0      | 0.3   |
| 1.0       | 1      | 0      | 0.1   |
| 1.0       | 0      | 1      | 0.2   |
```

## Potential solutions (high level syntax)

To prevent collision with the `-` operator for negation, the formula could be checked for spaces. `y ~ a + b-foo` would handle `b-foo` as a variable (covariate) name, whereas `y ~ a + b - foo` would negate a variable named `foo`.

Alternatively, the formula could parse variable names inside of quotes, e.g., `y ~ a + "b-foo"`.

**Comment by matthewwardrop** [comment]
Hi!

Thanks for writing in to report the issue. Just like in a Python expression, `-` has special meaning and cannot be used without some kind of quoting. For example, in python `b-foo` means `b minus foo`. In a formula it means `b set difference foo`.

If you want to use the column `b-foo`, then just quote the column name. You can do this using: ``b-foo``.

```
import pandas
from formulaic import model_matrix

df = pandas.DataFrame({
    'y': [0, 1, 2],
    'a': ['A', 'B', 'C'],
    'b-foo': [0.3, 0.1, 0.2],
})

y, X = model_matrix("y ~ a + `b-foo`", df)
```

This outputs the desired module matrix :).

**Comment by erikr** [comment]
Thanks, this answers my question and resolves the issue. Did I miss it, or does the documentation not include this info?

**Comment by matthewwardrop** [comment]
It is there (see screenshot below):

![image](https://user-images.githubusercontent.com/124910/143786538-aac6849b-6a0f-42e1-bbc7-5d0abefdc5a5.png)

But perhaps not called out as much as it should be. The documentation will definitely be enriched in the future with how-to guides/etc once I find some time!

**Comment by erikr** [comment]
Thanks for helping me find that in the documentation! The table format is helpful.
