### ISSUE TITLE
Fix minimum dependencies and add CI

### ISSUE THREAD

**Issue by lorentzenchr** [matthewwardrop/formulaic#52]
The current requirements from setup
```python
install_requires=[
        "astor",
        "interface_meta>=1.2",
        "numpy",
        "pandas",
        "scipy",
        "wrapt",
    ]
```
do not specify minimum versions (except for interface_meta). It would be nice to know the min versions and to have a CI run for them.

**Comment by matthewwardrop** [comment]
This should all be resolved now :).
