### ISSUE TITLE
Documentation: rendering issue for "X"s in "Formula Grammar" section

### ISSUE THREAD

**Issue by blthayer** [matthewwardrop/formulaic#57]
Hello! I'm considering using `formulaic`, and was taking a quick read through the documentation.

The tables on the [Formula Grammar](https://matthewwardrop.github.io/formulaic/basic/grammar/) page have check marks and what I assumed should be X-like symbols to indicate the presence or absence of a feature. The X's are not rendering properly for me either on Firefox or Chrome (image below from Firefox, Chrome similar but the boxes are empty instead of containing "01F" and "509"):

![image](https://user-images.githubusercontent.com/14652512/150689710-fcddf7e4-8974-4fe2-a0e1-977b33bd8544.png)

**Comment by matthewwardrop** [comment]
Oh... that's interesting. The default font used on your OS by these browsers must not include that symbol. That's especially odd given that the tick is included. Thanks for flagging!

**Comment by matthewwardrop** [comment]
Actually, out of curiosity, which OS (including version) are you using? Maybe this is just a matter of me needing to explicitly set the font in the browser.

**Comment by matthewwardrop** [comment]
And another follow up.... I've attempted to fix this by explicitly setting the font to Roboto in the theme settings. Did this help for you @ https://matthewwardrop.github.io/formulaic ?

**Comment by matthewwardrop** [comment]
Should now be fixed with f764b9d3ed21aa4d38e63a4b66bf2a1b449d5b37 . I replaced the unicode character for the cross with a charactor from an older unicode standard. I've tested this across a few more devices and things look good. Feel free to reopen if things still look broken!
