### ISSUE TITLE
ENH: Make sympy an optional dependency

### ISSUE THREAD

**Issue by bashtage** [matthewwardrop/formulaic#7]
SymPy depends on mpmath which does not appear to distribute binary modules.  This makes pip installation difficult on Windows, and possibly OSX.  SymPy doesn't seem fundamental to formulaic and only seems to be used for differentiation. 

Could this be converted to an optional feature that would raise if not available, as in

```
differentiate(...,sympy=True)

Traceback:
...
ImportError: SymPy must be installed to use this feature
```

**Comment by matthewwardrop** [comment]
Will make this change!
