### ISSUE TITLE
Spline Support like Patsy

### ISSUE THREAD

**Issue by petrhrobar** [matthewwardrop/formulaic#74]
Would it be possible to also implement (apart from already implemented interactions and category variable) splines feature:

```Patsy``` library does this really nicely.

[Example](https://patsy.readthedocs.io/en/latest/spline-regression.html)

**Comment by matthewwardrop** [comment]
Hi @petrhrobar ,

Formulaic already supports `poly` (orthogonal polynomial) and `bs` (basis splines) bases. Which additional spline bases do you need?

**Comment by petrhrobar** [comment]
Hey There,

COOL!. I was not aware of this. Is there any form of documentation covering the ```poly``` and ```bs```features?

**Comment by matthewwardrop** [comment]
Online documentation is a weak point... but we'll get there. Currently the only documentation is the grammar documentation, which indicates that support exists: https://matthewwardrop.github.io/formulaic/concepts/grammar/#transforms.

The API for these transforms is the same as patsy/R, and the inline documentation is thorough (e.g. https://github.com/matthewwardrop/formulaic/blob/main/formulaic/transforms/basis_spline.py#L37). The website documentation needs to be updated, but I already know this so I'll close this out for now :).

**Comment by petrhrobar** [comment]
Thanks for that.

Just a follow-up - how to change degrees of freedom in string formula:

```python
import seaborn as sns
from formulaic import Formula, formula
df = sns.load_dataset("tips")


Formula("total_bill ~ bs(size, df = 10)").get_model_matrix(df)
```

If I call the function itself, it works. however, having it changeable in the string is what I would like:

```python
from formulaic.transforms import basis_spline, poly
pd.DataFrame(basis_spline(df['size'], degree = 10)).values
```

**Comment by matthewwardrop** [comment]
Hi again!

The `bs` function in the formula is literally `basis_spline`... so you would pass the arguments through directly. For example:

```
from formulaic.transforms import basis_spline, poly
pd.DataFrame(basis_spline(df['size'], degree = 10)).values
```

would be achieved using:

```
from formulaic import Formula
Formula("bs(size, degree = 10)").get_model_matrix(df)
```

Does this not work for you?

**Comment by matthewwardrop** [comment]
Ah... I see. There's a bug in the stateful evaluation that attempts to treat the `10` constant as a column to be evaluated. I'll resolve that ahead of the next release!

**Comment by matthewwardrop** [comment]
The issue above was due to a bug / issue in astor <0.8. I bumped the dependency, and things should work now.
