### ISSUE TITLE
Supporting pandas 1.1 ?

### ISSUE THREAD

**Issue by AbdealiJK** [matthewwardrop/formulaic#79]
I saw that in v0.3+ pandas>1.2 is required.
Just wanted to check if that is the actual minimum or is it possible to support pandas 1.1.x series also as my organization requires me to use the older version of pandas.

Would be great if lower pandas versions can be supported - For now, I think I will have to go back to formulaic 0.2.x as a workaround

**Comment by matthewwardrop** [comment]
Fix in https://github.com/matthewwardrop/formulaic/commit/d8d4fda7479f24e6c5e3c2ec68dd257535a21304 . Should be released in formulaic 0.4 soon.

Thanks again for reaching out.

**Comment by AbdealiJK** [comment]
Thanks for looking into it !

**Comment by matthewwardrop** [comment]
Sorry for the delay! 0.4.0 has now been released :).
