### ISSUE TITLE
access dataframe index?

### ISSUE THREAD

**Issue by amichuda** [matthewwardrop/formulaic#84]
Is there some way to access index within a formula? I'd like to create dummies from the index without reset_index? So something like this:

```
"y ~ C(index.get_level_values(0))"
```

**Comment by matthewwardrop** [comment]
Hi @amichuda! Thanks for reaching out.

This is possible pretty easily using:
```
import pandas
import formulaic

df = pandas.DataFrame({'a': [1,2,3,4], 'b': list('aabb')}).set_index('b')

formulaic.model_matrix("C(a.index.get_level_values(0))", df)
```

If `df` is itself in the namespace, which it is if you use `model_matrix` or manually pass it through the `.get_model_matrix()` methods as context, you can also do:
```
formulaic.model_matrix("C(df.index.get_level_values(0))", df)
```

Marking as closed for now. Feel free to reopen if this doesn't answer your question.
